name: Проверка API-тестов

on:
  push:
    branches:
      - api-tests
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_file:
          - test_create_courier.py
          - test_login_courier.py
          - test_create_order.py
          - test_orders_list.py
          - test_delete_courier.py
          - test_accept_order.py
          - test_get_order_by_track.py

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Запустить тесты
        run: pytest tests/${{ matrix.test_file }} -vv -rA --tb=short --alluredir=allure_results | tee pytest-output.txt
      - name: Сохранить вывод pytest
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-${{ matrix.test_file }}
          path: pytest-output.txt
